name: 2. Pull Requests Tests
run-name: Pull Request from ${{ github.event.workflow_run.head_branch || github.head_ref || github.ref_name }} â†’ ${{ github.base_ref }}

on:
  workflow_run:
    workflows: ["1. Quality Assurance"]
    types:
      - completed
  # push:
  #   branches:
  #     - feature/**
  #     - develop
  # push:
  #   branches-ignore:
  #     - main

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

permissions:
  contents: write       # â†’ permite criar e atualizar tags, commits e pushes no repositÃ³rio.
  pull-requests: write  # â†’ se precisar criar ou atualizar pull requests
  checks: read          # â†’ se precisar ler check runs

jobs:
  app:  
    if: >
      ${{
        github.event.workflow_run.conclusion == 'success'
        && github.event.workflow_run.head_branch != 'main'
      }}

    uses: heliomarpm/actions-flow/.github/workflows/cd-pull-request.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      pr_body: |
        ðŸš€ Pull Request Automatizado
        
        {{QUALITY_GATE_RESULT}}
